 const ActionTypes =  {
    SET_STATES : "SET_STATES",
    SET_MESOREGIONS : "SET_MESOREGIONS",
    SET_CITY : "SET_CITY",
    SET_NEIGHBOURHOOD: "SET_NEIGHBOURHOOD",
    SET_PROPERTY:"SET_PROPERTY",
    SET_MAP:"SET_MAP"
}
export default ActionTypes